llm:
  api_type: "openai"  # or azure / ollama / groq etc.
  model: "gpt-4o"  # or gpt-3.5-turbo
  base_url: "https://api.rcouyi.com/v1"  # or forward url / other llm url
  api_key: "sk-olHf1RqTJBQvCDqX2d2dEd4c101741CfAa430c0b9d2368E3"